/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  전체: [{ type: 'autogenerated', dirName: '.' }],
  강주혁: [{ type: 'autogenerated', dirName: '강주혁' }],
  이학림: [{ type: 'autogenerated', dirName: '이학림' }],
  송은수: [{ type: 'autogenerated', dirName: '송은수' }],
  민세림: [{ type: 'autogenerated', dirName: '민세림' }],
  박규성: [{ type: 'autogenerated', dirName: '박규성' }],
};

module.exports = sidebars;
